juju:
  channel: 3.6/stable
  agent-version: "3.6.13"
  model-defaults:
    logging-config: <root>=INFO; unit=DEBUG

providers:
  k8s:
    enable: true
    bootstrap: true
    channel: 1.32-classic/stable
    features:
      local-storage:
      load-balancer:
        enabled: true
        l2-mode: true
        cidrs: 10.64.0.0/16
    bootstrap-constraints:
      root-disk: 4G

  lxd:
    enable: true
    bootstrap: false
    channel: latest/stable

host:
  snaps:
    charmcraft:
      channel: 3.x/stable