apiVersion: v1
kind: Service
metadata:
  name: controller-service-lb
  # namespace: controller-k8s29
spec:
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: api-server
    port: 17070
    protocol: TCP
    targetPort: 17070
  selector:
    app.kubernetes.io/name: controller
  sessionAffinity: None
  type: LoadBalancer