{
 "title": "Spark dashboard",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "lokids", "label": "Loki datasource", "query": "loki" },
   {
    "name": "juju_unit",
    "label": "Juju unit",
    "query": {
     "query": "label_values(up{juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_application=~\"$juju_application\"},juju_unit)"
    }
   },
   { "name": "prometheusds", "label": "Prometheus datasource", "query": "prometheus" },
   { "name": "juju_model", "label": "juju model", "query": { "query": "label_values(up,juju_model)" } },
   {
    "name": "juju_model_uuid",
    "label": "Juju model uuid",
    "query": {
     "query": "label_values(up{juju_model=~\"$juju_model\"},juju_model_uuid)"
    }
   },
   {
    "name": "juju_application",
    "label": "juju application",
    "query": {
     "query": "label_values(up{juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\"},juju_application)"
    }
   },
   {
    "name": "spark_job_id",
    "label": "Spark Job Id",
    "query": {
     "query": "label_values(push_time_seconds{juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_application=~\"$juju_application\"},exported_job)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Block Manager (Driver)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Block Manager Memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "BlockManager_memory_maxMem_MB{exported_job=~\"$spark_job_id\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",role=\"driver\"}",
     "legendFormat": "Max Memory (MB)"
    },
    {
     "expr": "BlockManager_memory_maxOffHeapMem_MB{exported_job=~\"$spark_job_id\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",role=\"driver\"}",
     "legendFormat": "Max Off Heap Memory (MB)"
    },
    {
     "expr": "BlockManager_memory_maxOnHeapMem_MB{exported_job=~\"$spark_job_id\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",role=\"driver\"}",
     "legendFormat": "Max On Heap Memory (MB)"
    },
    {
     "expr": "BlockManager_memory_remainingMem_MB{exported_job=~\"$spark_job_id\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",role=\"driver\"}",
     "legendFormat": "Remaining Memory (MB)"
    }
   ]
  },
  {
   "title": "Block Manager Disk Memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "BlockManager_disk_diskSpaceUsed_MB{exported_job=~\"$spark_job_id\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",role=\"driver\"}",
     "legendFormat": "Disk Memory (MB)"
    }
   ]
  },
  { "title": "Hive External Catalog (Driver)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Hive External Catalog",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "HiveExternalCatalog_fileCacheHits{exported_job=~\"$spark_job_id\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",role=\"driver\"}",
     "legendFormat": "File Cache Hits"
    },
    {
     "expr": "HiveExternalCatalog_filesDiscovered{exported_job=~\"$spark_job_id\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",role=\"driver\"}",
     "legendFormat": "File Discovered"
    },
    {
     "expr": "HiveExternalCatalog_hiveClientCalls{exported_job=~\"$spark_job_id\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",role=\"driver\"}",
     "legendFormat": "Client Calls"
    },
    {
     "expr": "HiveExternalCatalog_parallelListingJobCount{exported_job=~\"$spark_job_id\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",role=\"driver\"}",
     "legendFormat": "Parallel Listing Jobs"
    },
    {
     "expr": "HiveExternalCatalog_partitionsFetched{exported_job=~\"$spark_job_id\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",role=\"driver\"}",
     "legendFormat": "Partitions Fetched"
    }
   ]
  },
  { "title": "Dag Scheduler (Driver)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "DAG Schedule Jobs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "DAGScheduler_job_activeJobs{exported_job=~\"$spark_job_id\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",role=\"driver\"}",
     "legendFormat": "Active Jobs"
    },
    {
     "expr": "DAGScheduler_job_allJobs{exported_job=~\"$spark_job_id\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\",role=\"driver\"}",
     "legendFormat": "All Jobs"
    }
   ]
  },
  {
   "title": "Stages Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "DAGScheduler_stage_failedStages{role=\"driver\", exported_job=~\"$spark_job_id\"}",
     "legendFormat": "Failed Stages"
    },
    {
     "expr": "DAGScheduler_stage_runningStages{role=\"driver\", exported_job=~\"$spark_job_id\"}",
     "legendFormat": "Running Stages"
    },
    {
     "expr": "DAGScheduler_stage_waitingStages{role=\"driver\", exported_job=~\"$spark_job_id\"}",
     "legendFormat": "Waiting Stages"
    }
   ]
  },
  { "title": "Memory Metrics (Driver)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "JVM Executor Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "ExecutorMetrics_DirectPoolMemory{role=\"driver\", exported_job=~\"$spark_job_id\"}",
     "legendFormat": "Direct Pool Memory"
    },
    {
     "expr": "ExecutorMetrics_JVMHeapMemory{role=\"driver\", exported_job=~\"$spark_job_id\"}",
     "legendFormat": "JVM Heap Memory"
    },
    {
     "expr": "ExecutorMetrics_JVMOffHeapMemory{role=\"driver\", exported_job=~\"$spark_job_id\"}",
     "legendFormat": "JVM Off Heap Memory"
    },
    {
     "expr": "ExecutorMetrics_OffHeapExecutionMemory{role=\"driver\", exported_job=~\"$spark_job_id\"}",
     "legendFormat": "JVM Off Heap Execution Memory"
    },
    {
     "expr": "ExecutorMetrics_OnHeapStorageMemory{role=\"driver\", exported_job=~\"$spark_job_id\"}",
     "legendFormat": "JVM On Heap Storage Memory"
    },
    {
     "expr": "ExecutorMetrics_OnHeapExecutionMemory{role=\"driver\", exported_job=~\"$spark_job_id\"}",
     "legendFormat": "JVM On Heap Execution Memory"
    }
   ]
  },
  { "title": "Executors Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Executor Read and Writes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "executor_bytesRead{role=\"executor\", exported_job=~\"$spark_job_id\"}",
     "legendFormat": "Bytes Reads (#Executor {{number}})"
    },
    {
     "expr": "executor_bytesWritten{role=\"executor\", exported_job=~\"$spark_job_id\"}",
     "legendFormat": "Bytes Written (#Executor {{number}})"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "ExecutorMetrics_JVMHeapMemory{role=\"executor\", exported_job=~\"$spark_job_id\"}",
     "legendFormat": "JVM Heap Memory #{{number}}"
    },
    {
     "expr": "ExecutorMetrics_JVMOffHeapMemory{role=\"executor\", exported_job=~\"$spark_job_id\"}",
     "legendFormat": "JVM Off Heap Memory #{{number}}"
    }
   ]
  },
  {
   "title": "Executors Runtime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "rate(executor_runTime{role=\"executor\", exported_job=~\"$spark_job_id\"}[$__rate_interval])",
     "legendFormat": "Runtime (Executor #{{number}})"
    }
   ]
  },
  {
   "title": "Shuffle Reads/Writes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "targets": [
    {
     "expr": "executor_shuffleBytesWritten{role=\"executor\", exported_job=~\"$spark_job_id\"}",
     "legendFormat": "Shuffle Bytes Writes (Executor #{{number}})"
    },
    {
     "expr": "executor_shuffleLocalBytesRead{role=\"executor\", exported_job=~\"$spark_job_id\"}",
     "legendFormat": "Shuffle Local Bytes Reads (Executor #{{number}})"
    },
    {
     "expr": "executor_shuffleRemoteBytesRead{role=\"executor\", exported_job=~\"$spark_job_id\"}",
     "legendFormat": "Shuffle Remote Bytes Reads (Executor #{{number}})"
    }
   ]
  },
  {
   "title": "GC counts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "targets": [
    {
     "expr": "increase(ExecutorMetrics_MinorGCCount{role=\"executor\", exported_job=~\"$spark_job_id\"}[$__rate_interval])",
     "legendFormat": "Minor GC Count (Executor #{{number}}"
    },
    {
     "expr": "increase(ExecutorMetrics_MajorGCCount{role=\"executor\", exported_job=~\"$spark_job_id\"}[$__rate_interval])",
     "legendFormat": "Major GC Count (Executor #{{number}}"
    }
   ]
  },
  {
   "title": "GC Time Spend",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "targets": [
    {
     "expr": "rate(ExecutorMetrics_MajorGCTime{role=\"executor\", exported_job=~\"$spark_job_id\"}[$__rate_interval])",
     "legendFormat": "Major GC time (Executor #{{number}})"
    },
    {
     "expr": "rate(ExecutorMetrics_MinorGCTime{role=\"executor\", exported_job=~\"$spark_job_id\"}[$__rate_interval])",
     "legendFormat": "Minor GC time (Executor #{{number}})"
    },
    {
     "expr": "rate(ExecutorMetrics_TotalGCTime{role=\"executor\", exported_job=~\"$spark_job_id\"}[$__rate_interval])",
     "legendFormat": "Total GC time (Executor #{{number}})"
    }
   ]
  }
 ]
}