# Copyright 2024 Canonical Ltd.
# See LICENSE file for licensing details.

name: Check code and run unit tests

on:
  workflow_call:

jobs:
  checks:
    name: Code checks
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    strategy:
      fail-fast: true
      matrix:
        python-version:
          - "3.10"
          - "3.12"
    steps:
      - id: checkout
        name: Checkout repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - id: setup-python
        name: Setup Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: ${{matrix.python-version}}
          architecture: x64
      - name: Install tox & poetry
        run: |
          pipx install tox
          pipx install poetry

      - uses: terraform-linters/setup-tflint@6e1e0642c0289bd619021bf6b34e3c08ed1e005a # v6
        name: Setup TFLint

      - id: code-checks
        name: Make sure the code follows conventions and tests correctly
        run: |
          cd python && tox -e lint

      - id: tests-unit
        name: Run Unittests
        run: |
          cd python && tox -e unit
