# Copyright 2024 Canonical Ltd.
# See LICENSE file for licensing details.

name: Reference Architecture Test

on:
  # To be replaced by either schedule run or on demand
  pull_request:

jobs:
  reference-architecture:
    name: Reference Architecture Test
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        cloud:
          - azure
    timeout-minutes: 120
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - id: setup-python
        name: Setup Python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: "3.10"
          architecture: x64
      - name: Setup operator environment
        uses: charmed-kubernetes/actions-operator@main
        with:
          juju-channel: "3.6/stable"
          provider: microk8s
          channel: 1.32-strict/stable
          bootstrap-options: "--agent-version 3.6.5"
          microk8s-group: snap_microk8s
          microk8s-addons: "rbac dns minio metallb:10.64.140.43-10.64.140.49"
      - id: setup-terraform
        name: Install terraform if needed
        run: |
          if ! [ -x "$(command -v terraform)" ]; then
            echo "Installing terraform from snap"
            sudo snap install terraform --classic
          fi
      - id: deploy
        name: Deploy Reference Architecture
        timeout-minutes: 35
        run: |
          cd python/tests/reference_architecture/${{ matrix.cloud }}
          
          source get-vars.sh
          
          terraform apply -auto-approve
          juju wait-for model spark --query='forEach(units, unit => unit.agent-status=="idle" && unit.workload-status=="active")' --timeout 30m0s
