# Copyright 2024 Canonical Ltd.
# See LICENSE file for licensing details.

name: Run CI tests on a PR

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:

jobs:
  # tests:
  #   name: Run CI tests on a PR
  #   uses: ./.github/workflows/ci-tests-minimal.yaml
  #   secrets: inherit
  #
  bench:
    runs-on: ubuntu-22.04
    steps:
      - name: (GitHub hosted) Free up disk space
        shell: bash
        run: |
          printf '\nDisk usage before cleanup\n'
          df --human-readable
          # Based on https://github.com/actions/runner-images/issues/2840#issuecomment-790492173
          rm -r /usr/share/dotnet
          rm -r /opt/hostedtoolcache/
          printf '\nDisk usage after cleanup\n'
          df --human-readable
      - name: Checkout repo
        uses: actions/checkout@v4
      - id: setup-python
        name: Setup Python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: "3.10"
          architecture: x64
      - name: Setup operator environment
        uses: charmed-kubernetes/actions-operator@main
        with:
          juju-channel: 3.6/stable
          provider: microk8s
          channel: 1.32-strict/stable
          microk8s-group: snap_microk8s
          microk8s-addons: "rbac dns minio metallb:10.64.140.43-10.64.140.49"
      - name: Install tox & poetry
        shell: bash
        run: |
          pip install tox
          pip install poetry
      - id: setup-terraform
        name: Install terraform if needed
        shell: bash
        run: |
          if ! [ -x "$(command -v terraform)" ]; then
            echo "Installing terraform from snap"
            sudo snap install terraform --classic
          fi
      - id: cache-image
        name: Cache Image Locally
        shell: bash
        run: |
          # Download image for avoiding time out
          IMAGE="ghcr.io/canonical/charmed-spark-kyuubi@sha256:9268d19a6eef91914e874734b320fab64908faf0f7adb8856be809bc60ecd1d0"

          docker pull $IMAGE
          docker save $IMAGE -o image.tar
          sudo microk8s ctr images import --base-name $IMAGE image.tar
          docker rmi $IMAGE
          rm image.tar
      - id: bench
        name: Run benchmarks
        shell: bash
        env:
          AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
          AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_KEY }}
        run: |
          juju list-models
          cd python && tox run -e benchmarks -- --backend terraform --storage-backend azure
