# Copyright 2025 Canonical Ltd.
# See LICENSE file for licensing details.

name: Release spark-k8s-test Python library

env:
  BRANCH: ${{ github.ref_name }}


on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10


jobs:
  publish-to-pypi:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/spark-k8s-test

    steps:
      - uses: actions/checkout@v4

      - name: Publish Python Package to PyPI
        uses: ./.github/actions/release-spark-k8s-test
