name: Sync docs from Discourse

on:
  workflow_dispatch:
  schedule:
    - cron: "53 0 * * *" # Daily at 00:53 UTC
  # Triggered on push to branch "main" by .github/workflows/release.yaml
  workflow_call:
  pull_request:

jobs:
  sync-docs:
    name: Open PR with docs changes (3.4)
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Open PR with docs changes
        uses: canonical/discourse-gatekeeper@main
        id: docs-pr
        with:
          discourse_host: discourse.charmhub.io
          discourse_api_username: ${{ secrets.DISCOURSE_API_USERNAME }}
          discourse_api_key: ${{ secrets.DISCOURSE_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dry_run: "true"
          charm_dir: "releases/3.4/yaml"

      - name: Show migrate output
        run: echo '${{ steps.docs-pr.outputs.migrate }}'
      - name: Show reconcile output
        run: echo '${{ steps.docs-pr.outputs.reconcile }}'
